### ISSUE TITLE
Set up boilerplate for web app

### ISSUE THREAD

**Issue by egeriis** [boost-me/engine#1]
- Create React app?
- Storybook?
- Redux?
  - reducer/action structure
- Flow/TypeScript

**Comment by casperstorm** [comment]
~~Most is setup now, however missing the final steps for Storybook to be working properly with TS (https://storybook.js.org/configurations/typescript-config/)~~

Storybook is also working now properly with TS on this branch. Will merge make PR once done.
https://github.com/boost-me/engine/tree/feature/upload-component
